---
title: "Models"
author: "Ilaria Pia"
date: "29/06/2020"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library("rstan")
library(matrixStats)
options(mc.cores = parallel::detectCores())

library("raster")
library(Rcpp)
library(readxl)

source("functions.R")
sourceCpp("expCovariance.cpp")

load("finalTestTrainData")
load("finalDataPred")
```

### 2000 iterations

Whitefish, 1order , $1/l\sim t-student_4$
```{r}
wf1.t2000=readRDS("/home/piailari/Documents/thesis-pia/fits/fit_wf_final.rds")
m=posterior.check(wf1.t2000)

# train
ptrain=prediction(m, expCovariance, x1,x1,s1,s1 )

raster.plot(ptrain$Ef, "logdensity")
y00=ifelse(y1==0, 0.1,y1)
plot(log(y00/V1),ptrain$Ef ,xlab="obs", ylab="pred train", main="logdensity")
abline(0,1,col=2)

# test
ptest=prediction(m, expCovariance, x1,x2,s1,s2 )

raster.plot(ptest$Ef, "logdensity")
y00=ifelse(y2==0, 0.1,y2)
plot(log(y00/V2),ptest$Ef , xlab="obs", ylab="pred test", main="logdensity")
abline(0,1,col=2)
r=residual(ptest, x2, y2,V2)

# bigraster
 p=prediction(m, expCovariance, x,xpred,s,spred )
 saveRDS(p,"pred_wf_final.RData")
p=readRDS("pred_wf_final.RData")
p$summary_beta
par(mfrow=c(3,4))
for(i in 1:15) hist(p$betas[i,],main=paste0(rownames(p$summary_beta)[i]))
raster.plot(p$Ef, "Whitefish logdensity")

 pf=prediction(m, expCovariance, x,xpred.fut,s,spred.fut )
 saveRDS(pf,"pred_wf_final_fut.RData")
raster.plot(pf$Ef, "Whitefish future logdensity")

```

Vendace, 1order , $l\sim gamma$
```{r}
ve1.g2000=readRDS("/home/piailari/Documents/thesis-pia/fits/fit_ve_final.rds")
m=posterior.check(ve1.g2000)

# train
ptrain=prediction(m, expCovariance, x1,x1,s1,s1 )

raster.plot(ptrain$Ef, "logdensity")
y00=ifelse(y.v1==0, 0.1,y.v1)
plot(log(y00/V1),ptrain$Ef ,xlab="obs", ylab="pred train", main="logdensity")
abline(0,1,col=2)

# test
ptest=prediction(m, expCovariance, x1,x2,s1,s2 )

raster.plot(ptest$Ef, "logdensity")
y00=ifelse(y.v2==0, 0.1,y.v2)
plot(log(y00/V2),ptest$Ef , xlab="obs", ylab="pred test", main="logdensity")
abline(0,1,col=2)
r=residual(ptest, x2, y.v2,V2)

# bigraster
 p=prediction(m, expCovariance, x,xpred,s,spred )
 saveRDS(p,"pred_ve_final.RData")
p=readRDS("pred_ve_final.RData")
p$summary_beta
par(mfrow=c(3,4))
for(i in 1:15) hist(p$betas[i,],main=paste0(rownames(p$summary_beta)[i]))
raster.plot(p$Ef, "Vendace logdensity")

pf=prediction(m, expCovariance, x,xpred.fut,s,spred.fut )
saveRDS(pf,"pred_ve_final_fut.RData")
raster.plot(pf$Ef, "Vendace future logdensity")

```
